import "./globals.css";
import Footer from "./components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full">
      <body className="flex flex-col min-h-screen">
        <div className="flex-grow flex flex-col">
          {children}
        </div>
        <Footer/>
      </body>
    </html>
  );
}
